### ISSUE TITLE
settle time, from automation

### ISSUE THREAD

**Issue by catohagen** [arnonym/ha-plugins#115]
Hi

I added an wake-up alarm feature to my inhouse analog phone system.
So each line or room can call into home assistant and set a time, when this time is reached, a service call is made and it calls the room over and over until you pick up..

But when you pick up this call....there is this delay of maybe 2 seconds before you hear the TTS...
I have tried with or without "settle_time" and it seems to make no difference set to 0, or 1 or 10....gives same delay

here is the service call :

```
data:
  addon: 8cd50eef_ha-sip-next
  input:
    command: dial
    number: sip:port_01@192.168.1.160:5060
    ring_timeout: 15
    settle_time: 0
    menu:
      language: en-GB
      message: >
        {% set hours = states('input_datetime.set_alarm_time_port01')[0:-6] %}
        {% set mins = states('input_datetime.set_alarm_time_port01')[3:5] %}

        { hours }}:{{ mins }} This is an automated alarm. Dial 1 to disable this service. 
      choices:
        "1":
          message: |
            Stopping service
          action:
            domain: automation
            service: turn_off
            entity_id: automation.sip_port01_handset_alarm
          post_action: hangup
    webhook_to_call:
      call_established: sip_call_established
      call_disconnected: sip_call_disconnected
action: hassio.addon_stdin
```
is this a bug, or am I misunderstanding the settle_time variable ?
