### ISSUE TITLE
No incoming_call event

### ISSUE THREAD

**Issue by and7ey** [arnonym/ha-plugins#119]
I am trying to work with incoming calls.
I go to `/developer-tools/event` and input `incoming_call` as Listen to events value (also tried my webhook_id `sip_call_webhook_id`). 

Then make a call to my sip account. 

The call is seen at the sip log:

<details>

<summary>log</summary>

```
-end msg--
12:37:22.868           pjsua_core.c  .RX 334 bytes Request msg ACK/cseq=20 (rdata0x7f813f89f088) from UDP 5.135.215.43:5060:
ACK sip:homeassistant_id@192.168.1.110:5060;ob SIP/2.0
Via: SIP/2.0/UDP sip12.linphone.org;branch=z9hG4bK.2ZmjaSS891BgFNytmN18Q0BZUB;rport
Call-ID: Oo8xTSy8oz
From: <sip:incoming_caller@sip.linphone.org>;tag=vx7FWb9H~
To: <sip:homeassistant_id@sip.linphone.org>;tag=OnvqC9qUoOfd97DHDdqVnh8RTH.YcDLi
CSeq: 20 ACK
Max-Forwards: 69
Content-Length: 0


--end msg--
12:37:31.418           pjsua_core.c  .RX 303 bytes Request msg CANCEL/cseq=20 (rdata0x7f813f8a10a8) from UDP 5.135.215.43:5060:
CANCEL sip:homeassistant_id@192.168.1.110:5060;ob SIP/2.0
Via: SIP/2.0/UDP sip12.linphone.org;branch=z9hG4bK.0X0cBajB5SU58r8jmjB9Xy0BQa;rport
Call-ID: LkqtDZ4~HV
From: <sip:incoming_caller@sip.linphone.org>;tag=BFvbO15kv
To: <sip:homeassistant_id@sip.linphone.org>
CSeq: 20 CANCEL
Max-Forwards: 69
Content-Length: 0


--end msg--
12:37:31.418           pjsua_core.c  .TX 345 bytes Response msg 481/CANCEL/cseq=20 (tdta0x7f813fd55bb8) to UDP 5.135.215.43:5060:
SIP/2.0 481 Call/Transaction Does Not Exist
Via: SIP/2.0/UDP sip12.linphone.org;rport=5060;received=5.135.215.43;branch=z9hG4bK.0X0cBajB5SU58r8jmjB9Xy0BQa
Call-ID: LkqtDZ4~HV
From: <sip:incoming_caller@sip.linphone.org>;tag=BFvbO15kv
To: <sip:homeassistant_id@sip.linphone.org>;tag=z9hG4bK.0X0cBajB5SU58r8jmjB9Xy0BQa
CSeq: 20 CANCEL
Content-Length:  0


--end msg--
12:39:56.286           pjsua_core.c  .TX 520 bytes Request msg REGISTER/cseq=15323 (tdta0x7f813f87fc48) to UDP 5.135.215.43:5060:
REGISTER sip:sip.linphone.org SIP/2.0
Via: SIP/2.0/UDP 192.168.1.110:5060;rport;branch=z9hG4bKPj4voI1sFI15Lu0A8xd9WAjhsWE3.i5Bdy
Max-Forwards: 70
From: <sip:homeassistant_id@sip.linphone.org>;tag=9TrzRTxL5NOHYJ8wZk1gpI1VkfL12345
To: <sip:homeassistant_id@sip.linphone.org>
Call-ID: NLZNh7Sz8fRHFk-EDuoxYdwi3IfP6Bnv
CSeq: 15323 REGISTER
Contact: <sip:homeassistant_id@192.168.1.110:5060;ob>;+sip.ice
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Content-Length:  0


--end msg--
12:39:56.352           pjsua_core.c  .RX 534 bytes Response msg 401/REGISTER/cseq=15323 (rdata0x7f813f8a10b8) from UDP 5.135.215.43:5060:
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.1.110:5060;branch=z9hG4bKPj4voI1sFI15Lu0A8xd9WAjhsWE3.i5Bdy;rport=5060
Call-ID: NLZNh7Sz8fRHFk-EDuoxYdwi3IfP6Bnv
From: <sip:homeassistant_id@sip.linphone.org>;tag=9TrzRTxL5NOHYJ8wZk1gpI1VkfL12345
To: <sip:homeassistant_id@sip.linphone.org>;tag=5BgKNN6F5eDrm
CSeq: 15323 REGISTER
Server: Flexisip/2.3.3-47-g7d82ea0b (sofia-sip-nta/2.0)
WWW-Authenticate: Digest realm="sip.linphone.org",nonce="7EGm6gAAAACnh12345678+FYc2UAAAAA",opaque="+GNywA==",algorithm=MD5,qop="auth"
Content-Length: 0


--end msg--
12:39:56.352      sip_auth_client.c  ...Digest algorithm is "MD5"
12:39:56.352           pjsua_core.c  ....TX 804 bytes Request msg REGISTER/cseq=15324 (tdta0x7f813f87fc48) to UDP 5.135.215.43:5060:
REGISTER sip:sip.linphone.org SIP/2.0
Via: SIP/2.0/UDP 192.168.1.110:5060;rport;branch=z9hG4bKPj0NNVuaeu1RwdqMSiVs6UqAHB.VGSZJgG
Max-Forwards: 70
From: <sip:homeassistant_id@sip.linphone.org>;tag=9TrzRTxL5NOHYJ8wZk1gpI1VkfL12345
To: <sip:homeassistant_id@sip.linphone.org>
Call-ID: NLZNh7Sz8fRHFk-EDuoxYdwi3IfP6Bnv
CSeq: 15324 REGISTER
Contact: <sip:homeassistant_id@192.168.1.110:5060;ob>;+sip.ice
Expires: 300
Allow: PRACK, INVITE, ACK, BYE, CANCEL, UPDATE, INFO, SUBSCRIBE, NOTIFY, REFER, MESSAGE, OPTIONS
Authorization: Digest username="homeassistant_id", realm="sip.linphone.org", nonce="7EGm6gAAAACnh12345678+FYc2UAAAAA", uri="sip:sip.linphone.org", response="1f17a617820409c6405fcbaa99f67eec", algorithm=MD5, cnonce="gCLK1bXiglKrH12ooTlHuTZfnkMieAG", opaque="+GNywA==", qop=auth, nc=00000001
Content-Length:  0


--end msg--
12:39:56.423           pjsua_core.c  .RX 815 bytes Response msg 200/REGISTER/cseq=15324 (rdata0x7f813f8a10c8) from UDP 5.135.215.43:5060:
SIP/2.0 200 Registration successful
Via: SIP/2.0/UDP 192.168.1.110:5060;branch=z9hG4bKPj0NNVuaeu1RwdqMSiVs6UqAHB.VGSZJgG;rport=5060
Call-ID: NLZNh7Sz8fRHFk-EDuoxYdwi3IfP6Bnv
From: <sip:homeassistant_id@sip.linphone.org>;tag=9TrzRTxL5NOHYJ8wZk1gpI1VkfL12345
To: <sip:homeassistant_id@sip.linphone.org>;tag=DmtS3DDcepZDH
CSeq: 15324 REGISTER
Contact: <sip:homeassistant_id@192.168.1.110:5060;ob>;+sip.ice,"homeassistant_id"<sip:homeassistant_id@46.138.1.234:2164;transport=tls>;message-expires=2419200;+sip.instance="<urn:uuid:90364390-064f-0013-93ad-785bdd2e5474>";+org.linphone.specs="conference/1.0,ephemeral/1.1,groupchat/1.2,lime";pub-gruu="sip:homeassistant_id@sip.linphone.org;gr=urn:uuid:90364390-064f-0013-93ad-785bdd2e5474"
Expires: 300
Server: Flexisip/2.3.3-47-g7d82ea0b (sofia-sip-nta/2.0)
Supported: path,outbound
Content-Length: 0


--end msg--
12:39:56.423            pjsua_acc.c  ....SIP outbound status for acc 0 is not active
12:39:56.423            pjsua_acc.c  ....sip:homeassistant_id@sip.linphone.org: registration success, status=200 (Registration successful), will re-register in 300 seconds
12:39:56.423            pjsua_acc.c  ....Keep-alive timer started for acc 0, destination:5.135.215.43:5060, interval:14s
| 12:39:56.423702 [1] OnRegState: 200 Registration successful
```

</details>

The log contains some cancel and `SIP/2.0 481 Call/Transaction Does Not Exist` messages.

But no event is captured. What could be wrong here?

<details>

<summary>config</summary>

```
sip_global:
  port: 5060
  log_level: 5
  name_server: ""
  cache_dir: ""
sip:
  enabled: true
  registrar_uri: sip:sip.linphone.org
  id_uri: sip:my-username@sip.linphone.org
  realm: "*"
  user_name: my-username
  password: my-password
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
sip_2:
  enabled: false
sip_3:
  enabled: false
tts:
  platform: google_translate
  language: en
webhook:
  id: sip_call_webhook_id
```

</details>

**Comment by and7ey** [comment]
Upd. Ok, this is not event, but the following action is not triggered:

```
alias: SIP Incoming call
description: ""
trigger:
  - platform: webhook
    allowed_methods:
      - POST
    local_only: true
    webhook_id: sip_call_webhook_id
condition: []
action:
  - action: notify.persistent_notification
    data:
      message: data {{ trigger.event }}
mode: single
```
