### ISSUE TITLE
TTS is not working

### ISSUE THREAD

**Issue by sebska** [arnonym/ha-plugins#121]
Hi,

i can not get the addon to use TTS. 
It makes the call, but instead the message there come a loud "beep" instead of a text.

I have configured all: 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-++-
sip_global:
  port: 5060
  log_level: 5
  name_server: ""
  cache_dir: /config/audio
sip:
  enabled: true
  registrar_uri: sip:fritz.box
  id_uri: sip:homeassistant@fritz.box
  realm: "*"
  user_name: hot
  password: *********
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
sip_2:
  enabled: false
  registrar_uri: sip:fritz.box
  id_uri: sip:anotheruser@fritz.box
  realm: "*"
  user_name: anotheruser
  password: secret
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
sip_3:
  enabled: false
  registrar_uri: sip:192.168.178.10
  id_uri: ""
  realm: "*"
  user_name: ""
  password: ""
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
tts:
  platform: google_translate
  language: en
webhook:
  id: sip_call_webhook_id
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

My automation:
+++++++++++++++++++++++++++++++++++++++++++
alias: Telefonanruf intern Test
description: ""
triggers:
  - entity_id:
      - input_button.telefonanruf_test
    from: null
    trigger: state
conditions: []
actions:
  - data_template:
      addon: c7744bff_ha-sip
      input:
        command: dial
        number: sip:**610@fritz.box
        ring_timeout: 30
        menu:
          message: test
          tts_language: en
    action: hassio.addon_stdin
mode: single
+++++++++++++++++++++++++++++++++++++++++++

the Log shows:

.........................................................................................................................
| 13:39:39.716932 [1] Call is established.
| 13:39:39.717204 [ ] Calling webhook sip_call_webhook_id with data {'event': 'call_established', 'caller': 'sip:**610@fritz.box', 'parsed_caller': '**610', 'sip_account': 1}
| 13:39:39.740887 [ ] Webhook response 200 b''
| 13:39:39.741416 [1] Playing message: test
| 13:39:39.761030 [ ] Error getting tts file 500 b'500: Internal Server Error'
13:39:39.761            pjsua_aud.c  Creating file player: /ha-sip/sound/answer.wav..
13:39:39.761           wav_player.c  .File player '/ha-sip/sound/answer.wav' created: samp.rate=44100, ch=1, bufsize=4KB, filesize=176KB
13:39:39.761            pjsua_aud.c  .Player created, id=0, slot=2
13:39:39.761            pjsua_aud.c  Conf connect: 2 --> 1
13:39:39.761           conference.c  .Port 2 (/ha-sip/sound/answer.wav) transmitting to port 1 (sip:**610@fritz.box)
| 13:39:39.762018 [1] No action supplied
............................................................................................................................

so it seems there is somthing wrong with "getting tts file......"

Can anyone help with that?

Sebastian

**Comment by ma-xyz** [comment]
i can unfortunately not help, only report the exact same issue :-(

configuration:
```
sip_global:
  port: 5062
  log_level: 5
  name_server: ""
  cache_dir: /config/ha-sip-audio/
sip:
  enabled: true
  registrar_uri: sip:192.168.1.101
  id_uri: sip:9004@192.168.1.101
  realm: "*"
  user_name: "9004"
  password: "9004"
  answer_mode: accept
  settle_time: 1
  incoming_call_file: /config/sip-1-incoming.yaml
sip_2:
  enabled: false
  registrar_uri: sip:fritz.box
  id_uri: sip:anotheruser@fritz.box
  realm: "*"
  user_name: anotheruser
  password: secret
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
sip_3:
  enabled: false
  registrar_uri: sip:192.168.178.10
  id_uri: ""
  realm: "*"
  user_name: ""
  password: ""
  answer_mode: listen
  settle_time: 1
  incoming_call_file: ""
tts:
  platform: google_translate
  language: en
webhook:
  id: sip_call_webhook_id
```

log:
```
...
| 11:21:01.154197 [1] Playing message: Please enter your access code
| 11:21:01.180619 [ ] Error getting tts file 500 b'500: Internal Server Error'
...
```

/config/sip-1-incoming.yaml:
```
# allowed_numbers: # list of numbers which will be answered. If removed all numbers will be accepted
#     - "5551234456"
#    - "5559876543"
#     - "555{*}" # matches every number starting with 555
#     - "555{?}" # matches every number starting with 555 which is 4 digits long
# blocked_numbers: # alternatively you can specify the numbers not to be answered. You can't have both.
#    - "5551234456"
#    - "5559876543"
answer_after: 0 # time in seconds after the call is answered (optional, defaults to 0)
# webhook_to_call: # web-hook IDs which you can listen on in your actions (additional to the global web-hook)
#     call_established: another_webhook_id # can be all the same, or different
#     entered_menu: another_webhook_id
#     dtmf_digit: another_webhook_id
#     call_disconnected: another_webhook_id
menu:
    message: Please enter your access code
    choices_are_pin: true
    choices:
        '1234':
            id: owner
            message: Welcome beautiful.
            post_action: hangup
        '5432':
            id: maintenance
            message: Your entrance has been logged.
            post_action: hangup
        'default':
            id: wrong_code
            message: Wrong code, please try again
            post_action: return
```

ha versions:
```
Core 2024.10.3
Supervisor 2024.10.2
Operating System 13.2
Frontend 20241002.3
```

/config/ha-sip-audio/ is existing

google tts is working as such (when adding it to home assitant default voice assistant and use "try voice" it works at least)

cheers
michi
