### ISSUE TITLE
Command to listen and record established call to file

### ISSUE THREAD

**Issue by marvinhinz** [arnonym/ha-plugins#128]
Hi!

Im using this addon to control my dahua vto doorbell. Currently i have a setup that picks up every call and plays some waiting music, and notifies me via home assistant. Im also using https://github.com/felipecrs/dahua-vto-on-home-assistant/ (without the asterisk part) to enable two way talking using frigate. 

When someone rings, and i tap on the phone notification it takes me to the frigate card in the companion app where i can push a button to either cancel the call, or answer it. Answering cancels the sip call so i can use the two way rtsp stream. 

Very happy how it works right now :)

I just had the idea it would be nice when the waiting music call times out without an answer or cancel from me, to have the doorbell play a short soundfile or tts at the end like "it seems no one is at home right now, you can leave a message after the beep.".

Something like this maybe?

```
    - action: hassio.addon_stdin
      data:
        addon: c7744bff_ha-sip
        input:
          command: record_audio
          number: "{{ trigger.json.parsed_caller }}"
          destination_folder: /config/doorbell/recordings/ # filename should be generated ex. 2025-01-01_12:30.wav
          max_length: 30
```

Do you think this is feasible? If i have some time ill try to make a first draft.
