### ISSUE TITLE
Inspired by HA Blog entry "World's most private voice assistant" Possible to use together with voice assistant support?

### ISSUE THREAD

**Issue by dreimer1986** [arnonym/ha-plugins#133]
I am very sure that I overread that question or somthing similar which has been asked in the past already.

Did you already think about useing not just TTS from HA, but STT, too to achieve kinda a voice assistant conversation? Coupled with PIN protection and full AI in the background this might allow quite some interesting possibilities coming true.

I ask becuase of this: https://www.home-assistant.io/voice_control/worlds-most-private-voice-assistant/ I was hoping that this works on other SIP Gateways/Router like my Fritz Box and a coupled FritzzPhone, but... I fear it does not...

**Comment by arnonym** [comment]
Not sure, but I guess you could call the voice assistant through the built-in SIP service (need to run ha-sip and that on different ports), and then connect the audio channels through the "bridge_audio" command? 

```yaml
            action:
                command: dial
                number: sip:ha@192.168.178.24:5061
                menu:
                    action:
                        command: bridge_audio
                        number: self
                        bridge_to: '**620'
```

Kinda like that, where `number` is the IP address and port where the internal sip server is listening, and `bridge_to` is the device number where you're calling from.

Not sure if this is still relevant for you, but please share your results, if you're trying this one.

**Comment by eporsche** [comment]
Got it to work. I am able to speak with the home assistant ai via voip.

```
alias: Bridge HA VoIP to Phone
sequence:
  - data:
      addon: local_ha-sip-next
      input:
        command: dial
        number: sip:[ha voip user]@[ha-voip-ip:port]
        webhook_to_call:
          call_established: ha_voip_connected
        ring_timeout: 30
        menu:
          message: Connecting to phone, please wait
          post_action: noop
    action: hassio.addon_stdin
  - wait_for_trigger:
      - webhook_id: ha_voip_connected
        trigger: webhook
        allowed_methods:
          - POST
          - PUT
        local_only: true
    timeout: 30
  - data:
      addon: local_ha-sip-next
      input:
        command: dial
        number: sip:[phone_number]@[sip-provider]
        webhook_to_call:
          call_established: phone_connected
        ring_timeout: 30
    action: hassio.addon_stdin
  - wait_for_trigger:
      - webhook_id: phone_connected
        trigger: webhook
        allowed_methods:
          - POST
          - PUT
        local_only: true
    timeout: 30
  - data:
      addon: local_ha-sip-next
      input:
        command: bridge_audio
        number: sip:[ha voip user]@[ha-voip-ip:port]
        bridge_to: sip:[phone_number]@[sip-provider]
    action: hassio.addon_stdin
mode: single
description: ""
```

**Comment by eporsche** [comment]
Added a pull request to the next repository: https://github.com/arnonym/ha-plugins-next/pull/3

**Comment by arnonym** [comment]
Can you please create the PR against the next branch on the main repo? Otherwise I see no way to have you as an contributor listed 🙂
 Am 24.08.2025 08:01 schrieb Erik Porsche ***@***.***>:
eporsche left a comment (arnonym/ha-plugins#133)

Added a pull request to the next repository: https://github.com/arnonym/ha-plugins-next/pull/3

**Comment by arnonym** [comment]
Would you like to create a introduction how to configure this with some screenshots, perhaps in a new .md file which can be linked from the readme? what also would be nice is an automation which connects you to the assistant when you make an incoming call

**Comment by eporsche** [comment]
Currently working on that use case. I want to call my home assistant from the car. One also needs an automation to drop the "internal" call - otherwise the homassistant voip satellite will keep the connection open. (Can be done with call_disconnected webhook)

**Comment by arnonym** [comment]
And thanks for the automation and the pointer to the free google service.

I changed your automation to use variables, to avoid the duplication of values:

```yaml
alias: Voip incoming call to Home Assistant AI
description: ""
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
      - PUT
    local_only: true
    webhook_id: sip_call_webhook_id
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.json.parsed_caller == answer_for and
              trigger.json.event == "incoming_call" }}
        sequence:
          - action: hassio.addon_stdin
            data:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "{{ trigger.json.internal_id }}"
                menu:
                  post_action: noop
          - data:
              addon: c7744bff_ha-sip
              input:
                command: dial
                number: "{{ ha_assistant_sip_url }}"
                ring_timeout: 30
                webhook_to_call:
                  call_established: incoming_voip_call_established
            action: hassio.addon_stdin
          - wait_for_trigger:
              - trigger: webhook
                allowed_methods:
                  - POST
                  - PUT
                local_only: true
                webhook_id: incoming_voip_call_established
            timeout:
              hours: 0
              minutes: 0
              seconds: 10
              milliseconds: 0
          - data:
              addon: c7744bff_ha-sip
              input:
                command: bridge_audio
                number: "{{ trigger.json.internal_id }}"
                bridge_to: "{{ ha_assistant_sip_url }}"
            action: hassio.addon_stdin
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.json.parsed_caller == answer_for and
              trigger.json.event == "call_disconnected" }}
        sequence:
          - action: hassio.addon_stdin
            data:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "{{ ha_assistant_sip_url }}"
variables:
  answer_for: "012346789"
  ha_assistant_sip_url: sip:ha@192.168.178.2:5070
mode: single
```
