### ISSUE TITLE
feature: callers name recoqnition based on vcards (using khard) 

### ISSUE THREAD

**Issue by Bram-diederik** [arnonym/ha-plugins#16]
Is it possible to add callers name (and vcard group) recognition based on vcards (with khard)?

asterisk does not have build in name  recognition (not ldap nor vcards) nor has home assistant any contact support. (I dont think that should be in home assistant its far from designed for that.  )

adding this feature is not only nice to get a name spoken out of the speakers when someone dails your home phone. 
but if multiple address books can be added and the address book found can be returned you can make  scripts on it.

for example transferring a call to the voicemail if its late and the person is not in the family and close friends group. 

khard expects all contacts in seperated vcards that can be placed in the /share/contacts/<addressbook>/ folder for example.

**Comment by Bram-diederik** [comment]
I hacked it together but some good integration would be nice 

add to asterisk
`exten => ###,n,System(/opt/khard/script.php ${CALLERID(num)})`

```
#!/usr/bin/php
<?php
$command = "";
$addressbook ="none";
$name="unknown";
$number = $argv[1];
#echo strpos($number,"+");

#make the number general
if (preg_match('/\+\d+/', $number)) {
   $number = substr($number, 3);

} else {
   $number = substr($number, 1);
}
/* Add redirection so we can get stderr. */
$handle = popen('export LC_ALL=en_US.UTF-8 && khard -c /opt/khard/config/khard.conf  '. $number. ' 2>/dev/null', 'r');
#echo "'$handle'; " . gettype($handle) . "\n";
$read = fread($handle, 2096);
$command = $command . $read;
pclose($handle);
#echo $command;

$pattern = "/Address book: (.*)/";
if(preg_match_all($pattern, $command, $matches)) {
  $addressbook = $matches[1][0];
#print_r($matches);
}
echo $addressbook;
file_put_contents("/opt/khard/addressbook", $addressbook);

$pattern = "/\d+\s{2,}([A-Za-z0-9].*)\s{2}\s.cell/";
if(preg_match_all($pattern, $command, $matches)) {
  $name = $matches[1][0];
#print_r($matches);
}
file_put_contents("/opt/khard/name", $name);



?>
```

```
sensor:
  - platform: command_line
    name: asterisk_caller
    command: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new user@host cat /opt/khard/name"
    name: asterisk_address_book
    command: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=accept-new user@host cat /opt/khard/address_book"
```

```
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.asterisk_caller
  - service: script.tts_starter
    data: {}
  - service: tts.google_translate_say
    data:
      entity_id: media_player.ha_speaker
      message: "Inkomende beller {{states('sensor.asterisk_caller')}} "
      language: nl

```
