### ISSUE TITLE
Monkey test on my voip phone fails

### ISSUE THREAD

**Issue by Bram-diederik** [arnonym/ha-plugins#21]
I use my voip phone in my bedroom to control my bedroom devices. triggered by incoming number. And if i fire lots of commando after each other (you know monkey just press the buttons) the addon can crash after running several actions.  

I use 2.1. (could not test this on my test environment with next because this requires lots of additional integration) 

aterisk passon 
```
exten => 4012,1,Log(NOTICE, switch fan slaapkamer)
exten => 4012,n,Set(CALLERID(NUM)=4012)
exten => 4012,n,Dial(PJSIP/6011)
exten => 4012,n,Hangup()
```

addon log
```

|   timeout: 300.0
|   parent_menu: *id001
| timeout_choice:
|   id: null
|   message: null
|   language: en
|   action: null
|   choices_are_pin: false
|   choices: null
|   default_choice: null
|   timeout_choice: null
|   post_action: hangup
|   timeout: 300.0
|   parent_menu: *id001
| post_action: noop
| timeout: 300.0
| parent_menu: null
| 
| Registering call with id 4012
| Incoming call  from  '<sip:4012@192.168.5.14>' to '<sip:6011@192.168.5.20;ob>' (parsed: '4012')
| Answer mode: LISTEN
| Calling webhook sip_call_webhook_id with data {'event': 'incoming_call', 'caller': '<sip:4012@192.168.5.14>', 'parsed_caller': '4012'}
| Webhook response 200 b''
| Early
| Got "answer" command for 4012
| Trigger answer of call (if not established already)
| Call will be answered now.
| onCallMediaState call info state 3
| Connected media 1
| Call connecting...
| Call connected
| onCallRxReinvite
| onCallRxOffer
| onCallMediaState call info state 5
| Connected media 1
| Call is established.
| Calling webhook sip_call_webhook_id with data {'event': 'call_established', 'caller': '<sip:4012@192.168.5.14>', 'parsed_caller': '4012'}
| Webhook response 200 b''
| Playing message: fan slaapkamer uit
| Calling home assistant service on domain script service turn_on with entity script.switch_fan_slaapkamer
| Service response 200 b'[{"entity_id":"script.switch_fan_slaapkamer","state":"on","attributes":{"last_triggered":"2022-11-07T15:42:31.484147+00:00","mode":"single","current":1,"friendly_name":"switch_fan_slaapkamer"},"last_changed":"2022-11-07T15:42:31.484282+00:00","last_updated":"2022-11-07T15:42:31.484282+00:00","context":{"id":"01GH9C3V1TEJ6TNXYKBM4ECV8R","parent_id":null,"user_id":"42ed58e0d09f4f77b4beb6c2469e4e65"}}]'
| Playback done.
| Scheduled post action: noop
| onCallRxReinvite
| onCallRxOffer
| onCallMediaState call info state 5
| Connected media 1
| Call disconnected
| Calling webhook sip_call_webhook_id with data {'event': 'call_disconnected', 'caller': '<sip:4012@192.168.5.14>', 'parsed_caller': '4012'}
| Webhook response 200 b''
| &id001
| id: null
| message: null
| language: en
| action: null
| choices_are_pin: false
| choices: {}
| default_choice:
|   id: null
|   message: Unknown option
|   language: en
|   action: null
|   choices_are_pin: false
|   choices: null
|   default_choice: null
|   timeout_choice: null
|   post_action: return
|   timeout: 300.0
|   parent_menu: *id001
| timeout_choice:
|   id: null
|   message: null
|   language: en
|   action: null
|   choices_are_pin: false
|   choices: null
|   default_choice: null
|   timeout_choice: null
|   post_action: hangup
|   timeout: 300.0
|   parent_menu: *id001
| post_action: noop
| timeout: 300.0
| parent_menu: null
| 
| Registering call with id 4012
| Incoming call  from  '<sip:4012@192.168.5.14>' to '<sip:6011@192.168.5.20;ob>' (parsed: '4012')
| Answer mode: LISTEN
| Calling webhook sip_call_webhook_id with data {'event': 'incoming_call', 'caller': '<sip:4012@192.168.5.14>', 'parsed_caller': '4012'}
| Webhook response 200 b''
python3: ../src/pjsip/sip_transport.c:842: pjsip_rx_data_free_cloned: Assertion `rdata' failed.
/run.sh: line 34:   225 Aborted                 (core dumped) python3 /ha-sip/main.py
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

part of the script used
```

      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4012' }}"
          - condition: state
            entity_id: switch.calex_smart_plug_nl_socket_1
            state: "on"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4012"
                timeout: 10
                menu:
                  message: fan slaapkamer uit
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.switch_fan_slaapkamer
                  post_action: hangup
            enabled: true
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4012' }}"
          - condition: state
            entity_id: switch.calex_smart_plug_nl_socket_1
            state: "off"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4012"
                timeout: 10
                menu:
                  message: fan slaapkamer aan
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.switch_fan_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4012"
            enabled: false
    default: []
    enabled: true
mode: single


```

full script

```

alias: asterisk_controller
description: lokaal inkomende calls om HA te bedienen
trigger:
  - platform: webhook
    webhook_id: sip_call_webhook_id
condition:
  - alias: incomming call
    condition: template
    value_template: " {{ trigger.json.event == 'incoming_call' }} "
    enabled: true
  - alias: incomming call
    condition: template
    value_template: " {{ trigger.json.parsed_caller != '5555' }} "
    enabled: true
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4000' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4000"
                timeout: 10
                menu:
                  message: mute slaapkamer
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.switch_snapclient_slaapkamer_toggle
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4000"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4001' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4001"
                timeout: 10
                menu:
                  message: unmute slaapkamer
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.unmute_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4001"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4002' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4002"
                timeout: 10
                menu:
                  message: brams chillere nummers
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.cast_brams_chillere_nummers_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4002"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4003' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4003"
                timeout: 10
                menu:
                  message: brams lekkere nummers
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.cast_brams_lekker_nummers_slaapkamer
                post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4003"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4004' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4004"
                timeout: 10
                menu:
                  message: reggae
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.cast_slaapkamer_reggae
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4004"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4005' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4005"
                timeout: 10
                menu:
                  message: soul and jazz
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.cast_slaapkamer_soul_n_jazz
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4005"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4006' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4006"
                timeout: 10
                menu:
                  message: arrow rock fm
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.cast_slaapkamer_arrow_rock_fm
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4006"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4007' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4007"
                timeout: 10
                menu:
                  message: nieuws en weer
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.anp_nieuws
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4007"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4008' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4008"
                timeout: 10
                menu:
                  message: volume omhoog
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.volume_slaapkamer_up
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4008"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4009' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4009"
                timeout: 10
                menu:
                  message: volume omlaag
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.volume_slaapkamer_down
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4009"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4010' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4010"
                timeout: 10
                menu:
                  message: cast spotify
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.snapcast_spotify_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4010"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4011' }}"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4011"
                timeout: 10
                menu:
                  message: cast mpd
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.snapcast_mpd_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4011"
            enabled: false
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4012' }}"
          - condition: state
            entity_id: switch.calex_smart_plug_nl_socket_1
            state: "on"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4012"
                timeout: 10
                menu:
                  message: fan slaapkamer uit
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.switch_fan_slaapkamer
                  post_action: hangup
            enabled: true
      - conditions:
          - condition: template
            value_template: "{{ trigger.json.parsed_caller == '4012' }}"
          - condition: state
            entity_id: switch.calex_smart_plug_nl_socket_1
            state: "off"
        sequence:
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: answer
                number: "4012"
                timeout: 10
                menu:
                  message: fan slaapkamer aan
                  action:
                    domain: script
                    service: turn_on
                    entity_id: script.switch_fan_slaapkamer
                  post_action: hangup
            enabled: true
          - delay:
              hours: 0
              minutes: 0
              seconds: 5
              milliseconds: 0
            enabled: false
          - service: hassio.addon_stdin
            data_template:
              addon: c7744bff_ha-sip
              input:
                command: hangup
                number: "4012"
            enabled: false
    default: []
    enabled: true
mode: single


```
