### ISSUE TITLE
Things I have discovered 

### ISSUE THREAD

**Issue by Dunkelschunkel** [arnonym/ha-plugins#40]
Hi @arnonym,
I just discovered your add-on and I am awestruck  at what you have created. I have been using home assistant for a couple of years and have been wondering just as long why there is no better integration with telephony features and SIP. Your add-on fills this gap beautifully and I am still at the beginning of discovering all the features the add-on has to offer.
That said, there are just some minor things to which you might have some insights.

**Submenu**
Is it possible to return to a previous menu or submenu to the parent menu? "post_action" only returns me back to the menu on the same level. Maybe I missed something in the documentation and the issues, once I went down a menu branch it is not possible to go the other way. 

**timeout**
Timeouts only work in the root menu, the first level of the menu. Default option works just fine. 

**message and templating**
In my scenario someone is calling home assistant and ha-sip answers the call. After entering the pin the person can choose from from a couple of options one of which would be the announcing of the state of some entities. When in answering mode and thus using the yaml-file templating seems not possible. Only the "service: hassio.addon_stdin" call would be able to do just that and therefor be able to announce the current state of en entity. I guess using an automation and a webhook i could end the call, call back after a short delay and then announce the information I wanted to retrieve. The only thing holding me back are the rates of calling from landline (home assistant) to mobile ;-)

My yaml for incoming calls looks something like shown below. I could not switch from owner-1 to owner or even to the main menu. The templatings attempts are also visible in the menu "mieter"
The timeout only works in main menu.

```
menu:
    message: Bitte Pin eingeben
    choices_are_pin: true
    timeout: 10
    choices:
        '9876:
          id: mieter
          message: Hallo Paul. Der "{{ states('input_boolean.heizbetrieb_gastezimmer') }}"" ist ! Mit 1 umschalten.
          post_action: hangup
        '12345678:
            id: owner
            message: Hallo Johannes. Wähle 1 für Vorsaal Oben oder 2 für Flur Mitte. Mit Raute beenden.
            post_action: noop
            choices:
                '1':
                    id: owner-1
                    message: Vorsaal Oben geschalten.
                    post_action: return
                '2':
                    id: owner-2
                    message: Flur Mitte geschalten.
                    post_action: return
```

A service call to a number to announce a state of an entity would look like this

```
service: hassio.addon_stdin
data:
    addon: c7744bff_ha-sip
    input:
        command: dial
        number: sip:**610@192.168.179.2
        webhook_to_call_after_call_was_established: another_webhook_id # web-hook id which you can listen on in your actions (deprecated)
        webhook_to_call: # web-hook IDs which you can listen on in your actions (additional to the global web-hook)
            call_established: another_webhook_id # can be all the same, or different
            entered_menu: another_webhook_id
            dtmf_digit: another_webhook_id
            call_disconnected: another_webhook_id
        ring_timeout: 15 # time to ring in seconds (optional, defaults to 300)
        sip_account: 1 # number of configured sip account: 1 or 2 
                       # (optional, defaults to first enabled sip account)
        menu:
            message: "{{ state_attr('input_boolean.heizbetrieb_gastezimmer', 'friendly_name') }}  ist {{ states('input_boolean.heizbetrieb_gastezimmer') }}"
```
I am looking forward to your response

Dunkelschunkel
