### ISSUE TITLE
Error: Unknown command: transfer

### ISSUE THREAD

**Issue by Hypercookie** [arnonym/ha-plugins#64]
Thanks for this addon, it truly is amazing!

When sending 
```yaml
service: hassio.addon_stdin
data:
  addon: 58bd5418_ha-sip
  input:
        command: 'transfer'
        number: '<number>'
        transfer_to: '<number>'
```

to the addon, instead of transfer, i get an error in the logs `Error: unknown command: transfer` 
Am I doing something wrong? Everything else is working fine for me. Btw, it does also not work without the " ' "
