### ISSUE TITLE
More than one digit codes possible?

### ISSUE THREAD

**Issue by EnerGeh** [arnonym/ha-plugins#7]
Hey, I found your project in the HA forums and it works out of the box for my use case. Thank you very much for your effort on making DTMF call tones usable in HA, this was another missing piece in my home automation paradise. :-)
Unfortunately, I'm not able to enter codes that are longer than one digit, that limits me to only 12 (1...9|*|#) possible codes but much more interesting: It could be used as a kind of "pin code" detection and offer endless possibilities with SIP and DTMF. :-)
Are you planning to implement this feature or is it possible to extend the digit detection to more digits and I simply missed the according configuration option? Give me a hint if I can help you out on this.

**Comment by arnonym** [comment]
Hi EnerGeh,

thanks for the feedback!

I see two use-cases in your issue, which would be

1. Add a PIN protection to a menu
2. Have menu entries consisting of more than one digit.

The reason I would not misuse 2 to achieve 1 is, that you would probably like to be told as soon as possible that the menu entry you've entered does not exist. If you do that with a PIN code, it's much easier to brute-force that.

Would you still need 2 if you have 1? We would need to add some validation for this, because having an entry with "1" and another with "10" would be impossible.

**Comment by EnerGeh** [comment]
Okay, I got your point. I never thought about the voice messages and especially about something like "invalid input". What I dream of is some kind of "DTMF to digit converter", but this is very unlikely your target with this integration.
In General the PIN protected menu sounds good, maybe there is some broader integration possible to fit my needs. E.g. like a top menu protection "Enter pin", where the only submenu entry is "start ha action" and that one is triggerd directly after PIN input (configurable at best).
A more than one digit menu then sounds as a nice to have. It is very unlikely that you will listen to a voice message with more than 12 options 😉

**Comment by arnonym** [comment]
Would that be triggered by a human or a machine in your use-case?

**Comment by EnerGeh** [comment]
Do you mean the PIN entry? That would be triggered by humans via a kind of keypad. So there has to be a error handling when someone enters the wrong pin.
But when I try to describe this use case more detailed, I feel more that I definetly like to have a converter that simply writes the DTMF digits into a variable so that I can work independently with this way of input. Even the voice part in these calls is not really needed and so maybe I misused your integration according its intention?!

**Comment by arnonym** [comment]
I'm still not sure what you want to accomplish. If you have the entered keys in a variable inside of the add-on, what would happen next? Probably you would need to feed that string back to home assistant somehow?

What would the error handling on a wrongly entered PIN would look like, if there is no sound output on the input device?

The intention of ha-sip was to solve a very specific use-case of mine, but I tried to keep it as flexible as possible for other use-cases. Currently I do not understand your use-case completely, so hard to say if there is a mismatch.

**Comment by arnonym** [comment]
Is this still something you want to discuss?

**Comment by EnerGeh** [comment]
Oh, I feel so sorry, I missed your last reply. Yes of course I'd like to discuss this further. As far as I understand your use case: You're using the menu in a kind of a "intelligent voice routing" (IVR) solution to accomplish stuff like "Press 1 to turn on the light, press 2 to open cover, press 3 to active sound system".
This is a very cool idea, but I'd like to use it as a more secure solution for the pin entry at my door access system: Currently, the access code is processed inside the door station and then the "access granted" or "access denied" output is triggered. What I'd prefer is: The door station triggers "someone asks for access" (this is configurable in the door station) and then, HA should call that door station, the call is picked up automatically (configurable in the door station), maybe a voice command announces "Please enter your access code", then the user can enter its PIN via DTMF.
This PIN could then be used in HA to accomplish: "User with limited access", "Access prohibited", "Access granted but logged", "Family access, disarm camera surveillance" and unlimited other use cases.
Maybe I was more clear in my description now? Sorry for being that unspecific in the last posts.

**Comment by arnonym** [comment]
Yes, that's much clearer. I came up with the following;

```yaml
service: hassio.addon_stdin
data_template:
  addon: c7744bff_ha-sip
  input:
    command: dial
    number: sip:**620@fritz.box
    menu:
      message: Please enter your access code
      protected:
        error_message: No.
        pins:
          '12345':
            id: owner
            message: Welcome beautiful.
          '45678':
            id: limited
            message: Please put the parcel under the doormat.
          '98765':
            id: logged
            message: Your access has been logged. 
```
After entering the correct PIN the Id would be sent to a webhook so you can react on that in home assistant.

Would that solve your use-case? I actually like the idea of having multiple PINs, so you know who leaked the PIN or entered the building.

**Comment by arnonym** [comment]
I noticed that the pin section is very similar on what we have with `choices`, so I had another idea:
"""yaml
service: hassio.addon_stdin
data_template:
  addon: c7744bff_ha-sip
  input:
    command: dial
    number: sip:**620@fritz.box
    menu:
      id: main
      message: Please enter your access code
      error_message: No.
      choices_are_pin: true
      choices:
        '12345':
          id: owner
          message: Welcome beautiful.
        '45678':
          id: limited
          message: Please put the parcel under the doormat.
        '98765':
          id: logged
          message: Your access has been logged. 
"""
I like that a bit better, because it does not introduce that special `protected` section.

What do you think?

**Comment by EnerGeh** [comment]
Both solutions are looking promising to me, where the second proposal seems to be more straight-forward and comparable to the current YAML configuration of the IVR menu. Did I get that right that both are blueprint proposals and you'd have to adjust the current source code to implement this?
The `error_message: no` option will prevent a "wrong input" announcement to the user in case the pin is incorrect or does it prevent the early trigger of "wrong input" if you dail a digit that is not used in a pin, e.g. pressing 2 while the allowed pin starts with 1, 3 or 9 as you mentioned earlier?
What happens if you trigger the right code? I assume you will hear the message and the webhook is triggered, right?
When you entered a typo, what would happen? Will the call end after the (in your example) fifth digit? Can you trigger another webhook to log a failed event?

**Comment by arnonym** [comment]
Yes, both are not implemented currently.

The error message is the message that is played after entering a wrong PIN. Maybe "No" was a bad example :-). Should've been something like "Wrong code, please try again.".

The early trigger of wrong input is deactivated with the `choices_are_pin: true` option. In this case you need to enter the number of digits in the longest specified PIN before triggering the error path.

Your assumption about the handling of the correct code is correct.

Currently after entering a wrong code and playing the `error_message` you would by able to try again. Maybe it makes sense to add more options here.

Also the idea of triggering the webhook for wrong inputs makes sense. 

This could be handled like that, and also the `error_message` option could be removed:

```yaml
service: hassio.addon_stdin
data_template:
    addon: c7744bff_ha-sip
    input:
        command: dial
        number: sip:**620@fritz.box
        menu:
            message: Please enter your access code
            choices_are_pin: true
            choices:
                '1234':
                    id: owner
                    message: Welcome beautiful.
                '5432':
                    id: maintenance
                    message: Your entrance has been logged.
                'default':
                    id: wrong_code
                    message: Wrong code, please try again
                    post_action: hangup
```

Very nice discussion we're having here!

**Comment by arnonym** [comment]
In regards of the dynamic creation of the commands to ha-sip I have to say I never did something like that, but I guess you could use some template data for that, Would like to know if you achieve that and add that to the docs.

Timeout is currently not handled, but I would put that on my To-Do list.

Which architecture do you run your home-assistant on? Probably one of aarch64 or amd64? I would like to provide a beta version for this on https://github.com/arnonym/ha-plugins-next and compiling the docker image for all architectures takes a really long time, so I would only compile the version you need for testing.

Aus welcher Gegend Deutschlands kommst du?

**Comment by EnerGeh** [comment]
Yes, I think template data should be possible in that context, I'll try this out and give feedback on this. I'd be very happy to contribute my 2ct to the docs!
In my opinion, a timeout is a must-have for the pin handling, but of course, this is something we can focus on after the beta tests.
I'm running a full home assistant os in kvm on a amd64 hardware but hopefully get my home assistant amber in a couple of weeks, so this would be arm64 I think. I'm really looking forward to amber so that I can switch this important part of our daily life to a dedicated hardware.
Ich komm aus der Südpfalz. Wenn du mal in der Gegend bist, sagst Bescheid, auch hier gibt es gutes Bier ;-)

**Comment by arnonym** [comment]
The first beta is now available on. Add https://github.com/arnonym/ha-plugins-next  to your add-on repositories and install the -next plugin after.

You need to change the addon bit in your action to `8cd50eef_ha-sip-next` like in the example below. Timeout option is already included. The time-out count-down starts when the message starts to play, so add some seconds if you have a long message.

Looking forward to your feedback!

```yaml
service: hassio.addon_stdin
data_template:
  addon: 8cd50eef_ha-sip-next
  input:
    command: dial
    number: sip:**620@fritz.box
    menu:
      message: Please enter your access code
      choices_are_pin: true
      timeout: 10
      choices:
        "1234":
          id: owner
          message: Welcome beautiful.
          post_action: hangup
        "5432":
          id: maintenance
          message: Your entrance has been logged.
          post_action: hangup
        default:
          id: wrong_code
          message: Wrong code, please try again
          post_action: return
```
