### ISSUE TITLE
Send variables to webhook/automation/script ?

### ISSUE THREAD

**Issue by catohagen** [arnonym/ha-plugins#79]
I was trying to see if passing variables would work, directly from the sip-1-incoming.yaml

this is testing of an audio control menu, and to be able to use the same script (one script for multiple purposes)
But I cant figure out if this is going through, or if I'm doing something wrong

'5':
id: audio_main
message: audio sub menu, select number
choices:
'1':
id: sub01
message: next playlist 
action:
domain: script
service: toggle
entity_id: script.sip_audio_control
service_data:
variables:
test: 665
post_action: return 1
'2':
id: sub02
message: previous playlist
action:
domain: script
service: toggle
entity_id: script.sip_audio_control
service_data:
variables:
test: 667
post_action: return 1

idea was to send use a variable to tell the script what to do, instead of having single scripts for every control..
Would this be possible to do ?

**Comment by arnonym** [comment]
I implemented that in version 3.4 available on the next repo at https://github.com/arnonym/ha-plugins-next

Can you add that additionally to your home-assistant and test if this is working for you? For that you need to copy your configuration from the ha-sip to the ha-sip-next add-on and change the slug in your automations from `c7744bff_ha-sip` to `8cd50eef_ha-sip-next`. Also stop ha-sip and run ha-sip-next. If your feedback is positive I will release that to the non-beta repo!

Example and syntax see:
https://github.com/arnonym/ha-plugins-next#trigger-services-through-dtmf-on-an-outgoing-call

**Comment by catohagen** [comment]
i tried installing, but got this

Failed to install add-on
Can't install agellhaus/amd64-ha-sip-next:3.4: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=3.4&fromImage=agellhaus%2Famd64-ha-sip-next&platform=linux%2Famd64: Not Found ("manifest for agellhaus/amd64-ha-sip-next:3.4 not found: manifest unknown: manifest unknown")

**Comment by arnonym** [comment]
I noticed I only built `-next` for aarch64 and not amd64. I will build the image now, will be available soon.

**Comment by catohagen** [comment]
variables seems to work fine, i get the 'test' variable to hold 665

```
        '5':
            id: audio_main
            message: audio sub menu, select number
            choices:
                '1':
                    id: sub01
                    message: next playlist 
                    action:
                        domain: script
                        service: turn_on
                        entity_id: script.sip_audio_control
                        service_data:
                            variables:
                                test: 665
```
