### ISSUE TITLE
Possibility to stop a playing audio/mp3 file 

### ISSUE THREAD

**Issue by catohagen** [arnonym/ha-plugins#83]
Would it be possible to add a way to somehow stop a mp3 from playing ?
As when using ha-sip to dial and bridge calls, when dialing there is just silence until you pick up, so I tried adding some "elevator music" while it calls, but the music continues to play when picking up or when the two calls are connected.

I do this :

```
        '4':
            id: call_04
            message: stand by, calling port 4
            audio_file: '/config/www/audio/elevator music.mp3'
            action:
                domain: automation
                service: trigger
                entity_id: automation.sip_make_call_to_port
                service_data:
                    variables:
                        target: port_04
            post_action: noop
```
The mp3 file starts playing while the other phone is ringing, but it would be nice if it could stop when the call is bridged...
