### ISSUE TITLE
Webhook alternatives in communicating with HA Core

### ISSUE THREAD

**Issue by LukasGrebe** [arnonym/ha-plugins#85]
I would like to act on incoming calls that could create security issues. however the official docs suggest not using web hooks for this purpose because they don't require authentication.
See https://www.home-assistant.io/docs/automation/trigger/#webhook-security

Are any of these addon HA Core communication methods implemented?
https://developers.home-assistant.io/docs/add-ons/communication#home-assistant-core

**Comment by arnonym** [comment]
If you use a random webhook name (e.g. an UUID) and mark the webhook as local only (so only trigger-able through your local network) you're IMHO already very safe, but in the end it's your responsibility to vouch for your security.

ha-sip can call a script after a call or after a keypress, so maybe you can use that for your application.

**Comment by LukasGrebe** [comment]
Thanks for the feedback! 
Could you point me to an example of using a script? Would I just place a .sh file or similar in my config folder that would then run within the sip docker container?

**Comment by arnonym** [comment]
It's not a shell script, but a home assistant script. I never used that myself, but here's an example from another user: https://github.com/arnonym/ha-plugins/issues/79#issuecomment-1885335852

**Comment by catohagen** [comment]
it might work with shell scripts too, but you have to set them up in HA first

configuration.yaml :

```
shell_command:
   my_funky_script: 'bash /config/my_script.sh'
```

but to run this shell command in HA are only
```
service: shell_command.my_funky_script
```
so i'm not sure what to put in `domain:`

```
        '5':
            id: shell_script
            message: run shell script
            choices:
                '1':
                    id: shell01
                    message: funky shell script 
                    action:
                        domain: ?
                        service: shell_command.my_funky_script
                       

```

**Comment by TheFes** [comment]
@catohagen 
`domain` is the part before the dot, `service` is the part after. So it should be

```yaml
            choices:
                '1':
                    id: shell01
                    message: funky shell script 
                    action:
                        domain: shell_command
                        service: my_funky_script
```
