### ISSUE TITLE
user error?: how to trigger a script using the  hassio.addon_stdin choice menu

### ISSUE THREAD

**Issue by Bram-diederik** [arnonym/ha-plugins#9]
Sorry for the intrusion but i just started with Home Assistant. Just after i finished my asterisk server so making this addon work was one of the 1st things i did. 

I have a use case. I want a wake up routine that calls me and If i press 1 News is spoken trough a mpd player and after that music is played. I use 2 mpd services for this one that plays the music and streams it using the internal httpd. a 2nd one switching between tts and the stream. (!MUSIC STOPS! "You have a call from ... " !MUSIC PLAYS! works fine Thank you) 

Now i have created a service to speak out my rss news feed. only i cant get it to be triggered from within the hassio.addon_stdin choice menu.

see attached script 
i cant get the service running. 

a link to more examples would be helpful. (I use cut past a lot)
```
alias: wekker
description: ''
trigger:
  - platform: time_pattern
    hours: '07'
    minutes: '00'
    seconds: '00'
    enabled: false
condition: []
action:
  - service: hassio.addon_stdin
    data_template:
      addon: c7744bff_ha-sip
      input:
        command: dial
        number: sip:6001@192.168.5.14
        menu:
          message: Good Morning. press one for news. two for music
          choices:
            '1':
              message: Have a good day.
              action:
                service: script.mpdsay
            '2':
              message: Have a nice day.
              action:
                service: script.mpdsay
                data: {}
mode: single
```

**Comment by arnonym** [comment]
You need to specify `domain` and `service` in your actions:

```yaml
action:
  domain: script
  service: turn_on
  entity_id: script.mpdsay
```
